series: GLFW Graphics
title: Basic 2d OpenGL program
author:
  name: IGME-RIT
  email: 
  github: igme-rit
description: A barebones 2d OpenGL program that renders a triangle to the screen.
language: C++
tags:
  - Graphics
extra_resources:
connections: